### ISSUE TITLE
Google map not visible on placelist.php for visitors

### ISSUE THREAD

**Issue by mpwt** [JustCarmen/justlight#27] opened 2016-10-03 15:45 UTC
If I check View -> Lists -> Place hierarchy (placelist.php) as an unregistred visitor I do not see the google map within webtrees 1.7.8 and Justlight theme 1.7.8. When I'm logged-in I can see it.

I have tested it with a Google maps API key V3 too but I do not see the map as visitor (ffp.bauschaffen.de/placelist.php).

Any idea? With other themes it works.

**Comment by JustCarmen** [comment] 2016-10-03 20:51
Confirmed. See the same thing happening on my own site. Didn't notice it before.

At the moment I have no idea what causes this error, but I know there are things changed in the core related to Google maps and I probably need to adjust some style or javascript settings. I wil post a fix when I've found the cause.

**Comment by JustCarmen** [comment] 2016-10-03 21:35
Don't know why but the commit isn't closed automatically. I've committed a fix a few minutes ago. It turned out to be a very simple fix: https://github.com/JustCarmen/justlight/commit/f6b12ef4dece0933c6eb104e334cdf4fbff23010

**Closed by JustCarmen** 2016-10-03 21:35 UTC
Labels: bug
